"""make task_id nullable in task_attachments

Revision ID: e1e67fd6fc7f
Revises: bdfae737f281
Create Date: 2026-06-21 22:38:33.683973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e67fd6fc7f'
down_revision: Union[str, Sequence[str], None] = 'bdfae737f281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.alter_column('task_attachments', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.alter_column('task_attachments', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    # ### end Alembic commands ###
