"""create_password_reset_otps_table

Revision ID: 2c1e37e163c9
Revises: b3f1a7d92e01
Create Date: 2026-06-17 00:11:44.372519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c1e37e163c9"
down_revision: Union[str, Sequence[str], None] = "b3f1a7d92e01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_reset_otps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("otp_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_reset_otps_email"),
        "password_reset_otps",
        ["email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_otps_id"), "password_reset_otps", ["id"], unique=False
    )

    op.create_table(
        "forgot_password_rate_limits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_forgot_password_rate_limits_email"),
        "forgot_password_rate_limits",
        ["email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_forgot_password_rate_limits_id"),
        "forgot_password_rate_limits",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_forgot_password_rate_limits_ip_address"),
        "forgot_password_rate_limits",
        ["ip_address"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_forgot_password_rate_limits_ip_address"),
        table_name="forgot_password_rate_limits",
    )
    op.drop_index(
        op.f("ix_forgot_password_rate_limits_id"),
        table_name="forgot_password_rate_limits",
    )
    op.drop_index(
        op.f("ix_forgot_password_rate_limits_email"),
        table_name="forgot_password_rate_limits",
    )
    op.drop_table("forgot_password_rate_limits")

    op.drop_index(op.f("ix_password_reset_otps_id"), table_name="password_reset_otps")
    op.drop_index(
        op.f("ix_password_reset_otps_email"), table_name="password_reset_otps"
    )
    op.drop_table("password_reset_otps")
    # ### end Alembic commands ###
