"""create_project_members_table

Revision ID: e22cc9544785
Revises: 1942d3cc85c5
Create Date: 2026-06-04 19:25:23.201542

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "e22cc9544785"
down_revision: Union[str, Sequence[str], None] = "1942d3cc85c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
